### ISSUE TITLE
Add Deliverable D3.1 ?

### ISSUE THREAD

**Issue by stain** [elixir-europe/by-covid-website#5]
Can we add Deliverable D3.1 to Zenodo+website? It was due last month so should be ready.

Co-ordinate with WP3 leaders Henning Hermjakob, Mari Kleemola to get right PDF.

**Comment by rajxir** [comment]
Thanks Stain. I will be working on the deliverables soon and will add the Zenodo link then.

**Comment by stain** [comment]
D3.1 now listed on https://by-covid.eu/outputs so closing
